version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: serverwod
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
    networks:
      - net

networks:
  net:
    driver: bridge