const expressionList = [
  'Beat around the bush',
  'Better late than never',
  'Bite the bullet',
  'Break a leg',
  'Hit the sack',
  'Miss the boat',
  'Pull someone\'s leg',
  'Pull yourself together',
  'So far so good',
  'Speak of the devil',
  'That\'s the last straw',
  'The best of both worlds',
  'Your guess is as good as mine',
  'A penny for your thoughts',
  'A perfect storm',
  'A picture is worth 1000 words',
  'Barking up the wrong tree',
  'Break the ice',
  'Costs an arm and a leg',
  'Don\'t put all your eggs in one basket',
  'A snowball effect',
  'Throw caution to the wind',
  'The elephant in the room',
  'The devil is in the details',
  'The ball is in your court',
  'An apple a day keeps the doctor away',
  'Calm before the storm',
  'Come rain or shine',
  'Curiosity killed the cat',
  'Don\'t beat a dead horse',
  'Have your head in the clouds',
  'Let sleeping dogs lie',
  'You can\'t make an omelet without breaking some eggs',
  'That ship has sailed',
];

export default expressionList;
